version: "3"
services:
  elasticsearch-v7.16.3:
    container_name: "elasticsearch"
    build:
      context: .
      dockerfile: ./dockerfiles/elasticsearch/Dockerfile
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - logger.deprecation.level=debug
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-v7.16.3-data:/usr/share/elasticsearch/data

  kibana-v7.16.3:
    image: docker.elastic.co/kibana/kibana:7.16.3
    ports:
      - "5601:5601"
    restart: always
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"

  database:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: ./dockerfiles/ruby/Dockerfile
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200/
      MYSQL_HOST: database
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - database
      - elasticsearch-v7.16.3

volumes:
  elasticsearch-v7.16.3-data:
    driver: local
